apiVersion: v1
kind: Pod
metadata:
  labels:
    app: debug-pod
  annotations:
    app: debug-pod
  name: debug
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: alpine
    name: debug